'use strict';
/**
 * POS router – drink / food token redemption at the event
 * POST /api/pos/redeem-entitlement  — idempotent
 * GET  /api/pos/status/:publicCode  — current token balances
 */

const express = require('express');
const router = express.Router();
const { authenticateToken } = require('../auth');
const { requireEventRole } = require('./middleware');
const db = require('../config/database');

/**
 * GET /api/pos/status/:publicCode
 * Returns current entitlement balances for a ticket.
 * Requires at minimum door_scanner role for the event.
 */
router.get('/status/:publicCode', authenticateToken, async (req, res, next) => {
  try {
    const result = await db.query(
      `SELECT t.public_code, t.drink_tokens_remaining, t.food_tokens_remaining,
              a.name AS attendee_name, al.name AS access_level_name,
              e.id AS event_id
       FROM tickets t
       LEFT JOIN attendees a ON a.id = t.attendee_id
       LEFT JOIN ticket_types tt ON tt.id = t.ticket_type_id
       LEFT JOIN access_levels al ON al.id = tt.access_level_id
       JOIN events e ON e.id = t.event_id
       WHERE t.public_code = $1 AND t.revoked_at IS NULL`,
      [req.params.publicCode],
      { queryName: 'pos_status_lookup', requestId: req.requestId }
    );
    if (!result.rows[0]) return res.status(404).json({ error: 'Ticket not found' });
    res.json(result.rows[0]);
  } catch (err) { next(err); }
});

/**
 * POST /api/pos/redeem-entitlement
 * Deducts one or more tokens from a ticket. Idempotent via idempotency_key.
 *
 * Body:
 *   public_code      string   — ticket public_code
 *   token_type       string   — "drink" | "food"
 *   quantity         number   — how many to redeem (default 1)
 *   idempotency_key  string   — UUID generated by the client
 *   device_id        string?  — scanner device identifier
 */
router.post('/redeem-entitlement', authenticateToken, async (req, res, next) => {
  const { public_code, token_type, quantity = 1, idempotency_key, device_id } = req.body;

  if (!public_code) return res.status(400).json({ error: 'public_code required' });
  if (!['drink', 'food'].includes(token_type)) return res.status(400).json({ error: 'token_type must be drink or food' });
  if (!idempotency_key) return res.status(400).json({ error: 'idempotency_key required' });
  if (!Number.isInteger(quantity) || quantity < 1 || quantity > 20)
    return res.status(400).json({ error: 'quantity must be 1-20' });

  const client = await db.pool.connect();
  try {
    await client.query('BEGIN');

    // Idempotency check — use a dedicated table to track redemptions
    const idempCheck = await client.query(
      `SELECT id, status FROM entitlement_redemptions
       WHERE idempotency_key = $1 FOR UPDATE`,
      [idempotency_key]
    );
    if (idempCheck.rows.length > 0) {
      await client.query('ROLLBACK');
      return res.json({ ...idempCheck.rows[0], idempotent: true });
    }

    // Load ticket (lock row)
    const col = token_type === 'drink' ? 'drink_tokens_remaining' : 'food_tokens_remaining';
    const ticketResult = await client.query(
      `SELECT t.id, t.event_id, t.${col} AS tokens_remaining
       FROM tickets t
       WHERE t.public_code = $1 AND t.revoked_at IS NULL
       FOR UPDATE`,
      [public_code]
    );
    if (!ticketResult.rows[0]) {
      await client.query('ROLLBACK');
      return res.status(404).json({ error: 'Ticket not found' });
    }

    const ticket = ticketResult.rows[0];

    // Role check — must be at least seller for this event
    const staffCheck = await client.query(
      `SELECT role FROM event_staff
       WHERE event_id = $1 AND user_id = $2 AND revoked_at IS NULL`,
      [ticket.event_id, req.user.id]
    );
    const isSuperAdmin = req.user.isAdmin;
    if (!isSuperAdmin && staffCheck.rows.length === 0) {
      await client.query('ROLLBACK');
      return res.status(403).json({ error: 'Not authorized for this event' });
    }

    if (ticket.tokens_remaining < quantity) {
      await client.query('ROLLBACK');
      return res.status(409).json({
        error: 'Insufficient tokens',
        tokens_remaining: ticket.tokens_remaining,
        requested: quantity,
      });
    }

    // Deduct tokens atomically
    await client.query(
      `UPDATE tickets SET ${col} = ${col} - $1, updated_at = NOW()
       WHERE id = $2`,
      [quantity, ticket.id]
    );

    // Record redemption for idempotency
    const newBalance = ticket.tokens_remaining - quantity;
    const redemption = await client.query(
      `INSERT INTO entitlement_redemptions
         (idempotency_key, ticket_id, token_type, quantity, redeemed_by_user_id, device_id, balance_after, status)
       VALUES ($1, $2, $3, $4, $5, $6, $7, 'success')
       RETURNING id, status, balance_after`,
      [idempotency_key, ticket.id, token_type, quantity, req.user.id, device_id ?? null, newBalance]
    );

    await client.query('COMMIT');

    res.json({
      success: true,
      token_type,
      quantity_redeemed: quantity,
      balance_after: newBalance,
      idempotency_key,
      idempotent: false,
    });
  } catch (err) {
    await client.query('ROLLBACK');
    next(err);
  } finally {
    client.release();
  }
});

module.exports = router;
